INSERT INTO `categories` (`id`, `category_name`) VALUES
(1, 'General Knowledge'),
(2, 'English'),
(3, 'Maths'),
(4, 'HTML'),
(5, 'Networking - OSI Layers');

INSERT INTO `questions` (`id`, `question_name`, `answer1`, `answer2`, `answer3`, `answer4`, `answer`,`question_type`, `category_id`) VALUES
(1, 'Which scientist discovered the radioactive element radium?', 'Isaac Newton', 'Albert Einstein', 'Benjamin Franklin', 'Marie Curie', '4','Multiple-choice', 1),
(2, 'What Galileo invented?', 'Barometer', 'Pendulum clock', 'Microscope', 'thermometer', '4','Text', 1),
(3, 'What James Watt invented?', 'Diving bell', 'Steam boat', 'Hot air balloon', 'rotary steam engine', '4','Text', 1),
(4, 'Who invented Jet Engine?', 'Sir Frank Whittle', 'Gottlieb Daimler', 'Roger Bacon', 'Lewis E. Waterman', '1','Multiple-choice', 1),
(5, 'Who invented Gunpowder?', 'G. Ferdinand Von Zeppelin', 'Sir Frank Whittle', 'Roger Bacon', 'Leo H Baekeland', '3','Multiple-choice', 1),
(6, 'In which decade was the telephone invented?', '1850s', '1860s', '1870s', '1880s', '3','Multiple-choice', 1),
(7, 'Who perfected GENETIC ENGINEERING?', 'Cohen & Boyer', 'Hunt & Davids', 'Sinclair & Roberts', 'Jaysson & Simons', '1','Multiple-choice', 1),
(8, 'When was the first elevator built?', '1743', '1739', '1760', '1785', '1','Text', 1),
(9, 'What charge card, developed in 1950, was the first to be accepted nationally in the US?', 'Visa', 'Discover', 'MasterCharge', 'Diners Club', '4','Multiple-choice', 1),
(10, 'What George Westinghouse invented?', 'Light bulb', 'Electric razor', 'Refrigerator', 'Railway air brakes', '4','Multiple-choice', 1),
(11, 'What is the synonym of VENT', 'Opening', 'Stodge', 'End', 'Past tense of go', '1','Multiple-choice', 2),
(12, 'What is correct meaning of proverb : To drive home', 'To find ones roots', 'To return to place of rest', 'Back to original position', 'To emphasise', '4','Multiple-choice', 2),
(13, 'What is correct meaning of proverb : To have an axe to grind', 'A private end to serve', 'To fail to arouse interest', 'To have no result', 'To work for both sides', '1','Multiple-choice', 2),
(14, 'Select the pair which has the same relationship -- LIGHT : BLIND', 'speech:dumb', 'language:deaf', 'tongue:sound', 'voice:vibration', '1','Multiple-choice', 2),
(15, 'Select the pair which has the same relationship -- THRUST : SPEAR', 'mangle:iron', 'scabbard:sword', 'bow:arrow', 'fence:epee', '4','Multiple-choice', 2),
(16, 'What is the synonym of Fast', 'abc', 'xyz', 'Quick', 'none', 'quick','Text', 2),
(17, 'What is the synonym of Clever', 'abc', 'Smart', 'Quick', 'none', 'smart','Text', 2),
(18, 'What is the synonym of Huge', 'abc', 'Large', 'Quick', 'none', 'large','Text', 2),
(19, 'What is the synonym of Pretty', 'Beautiful', 'xyz', 'Quick', 'none', 'beautiful','Text', 2),
(20, 'What is the synonym of Lady', 'abc', 'xyz', 'Quick', 'Woman', 'woman','Text', 2),
(21, 'What is the next prime number after 7?', '11', '13', '21', '9', '1','Multiple-choice', 3),
(22, 'The perimeter of a circle is also known as what?', 'To find ones root', 'To return to place of rest', 'Back to original position', 'circumference', 'circumference','Text', 3),
(23, '65 &#45; 43 = ?', '11', '13', '22', '9', '22','Text', 3),
(24, 'True or false? A convex shape curves outwards.', 'speech:dumb', 'language:deaf', 'tongue:sound', 'true', 'true','Text', 3),
(25, 'What does the square root of 144 equal?', '10', '13', '11', '12', '4','Multiple-choice', 3),
(26, 'True or false? Pi can be correctly written as a fraction.', 'abc', 'xyz', 'Quick', 'false', 'false','Text', 3),
(27, 'What comes after a million, billion and trillion?', 'abc', 'Smart', 'Quick', 'quadrillion', 'quadrillion','Text', 3),
(28, 'What does 3 squared equal?', '9', '6', '7', '12', '1','Multiple-choice', 3),
(29, 'True or false? -4 is a natural number.', 'Beautiful', 'xyz', 'Quick', 'none', 'false','Text', 3),
(30, '5 to the power of 0 equals what?', '1', '0', '3', '2', '1','Text', 3),
(31, 'A webpage displays a picture. What tag was used to display that picture?', 'picture', 'image', 'img', 'src', 'img','Text', 4),
(32, 'Which tag inserts a line horizontally on your web page?', '<hr>', '<line>', '<line direction=”horizontal”>', '<tr>', '1','Multiple-choice', 4),
(33, 'What should be the first tag in any HTML document?', '<head>', '<title>', '<html>', '<document>', '3','Multiple-choice', 4),
(34, 'Which tag allows you to add a row in a table?', '<td> and </td>', '<cr> and </cr>', '<th> and </th>', '<tr> and </tr>', '4','Multiple-choice', 4),
(35, 'How can you make a bulleted list?', '<list>', '<nl>', '<ul>', '<ol>', '3','Multiple-choice', 4),
(36, 'How can you make a numbered list?', '<dl>', '<ol>', '<list>', '<ul>', '2','Multiple-choice', 4),
(37, 'Which attribute is used to name an element uniquely?', 'class', 'id', 'dot', 'all of above', '2','Multiple-choice', 4),
(38, 'Which tag creates a check box for a form in HTML?', '<checkbox>', '<input type=”checkbox”>', '<input=checkbox>', '<input checkbox>', '2','Multiple-choice', 4),
(39, 'Which of the following is not a pair tag?', '<p>', '<u>', '<i>', '<img>', '4','Multiple-choice', 4),
(40, 'There are how many different of heading tags in HTML?', '4', '5', '6', '7', '6','Text', 4),
(41, 'The _ translates internet domain and host names to IP address.', 'domain name system', 'routing information protocol', 'network time protocol', 'internet relay chat', '1','Multiple-choice', 5),
(42, 'Application layer protocol defines', 'types of messages exchanged', 'message format, syntax and semantics', 'rules for when and how processes send and respond to messages', 'all of the mentioned', '4','Multiple-choice', 5),
(43, 'Which one of the following protocol delivers/stores mail to receiver server?', 'simple mail transfer protocol', 'post office protocol', 'internet mail access protocol', 'hypertext transfer protocol', '1','Multiple-choice', 5),
(44, 'Which one of the following is not an application layer protocol?', 'media gateway protocol', 'dynamic host configuration protocol', 'resource reservation protocol', 'session initiation protocol', '3','Multiple-choice', 5),
(45, 'Which protocol is a signaling communication protocol used for controlling multimedia communication sessions?', 'session initiation protocol', 'session modeling protocol', 'session maintenance protocol', 'none of the mentione', '1','Multiple-choice', 5),
(46, 'When displaying a web page, the application layer uses the', 'HTTP protocol', 'FTP protocol', 'SMTP protocol', 'none of the mentioned', '1','Multiple-choice', 5),
(47, 'TCP port 25 is used by?', 'SMTP', 'SNTP', 'SNMP', 'HTTP', '1','Multiple-choice', 5),
(48, 'On ____ layer every device has a logical address know as IP address.?', 'Network', 'Physical', 'Data link', 'Application', 'network','Text', 5),
(49, 'The addresses use for communication on data-link layer is _', 'MAC', 'IP Address', 'Frames', 'Bits', '1','Multiple-choice', 5),
(50, 'HTTPS uses the TCP port ___', '443', '80', '8080', '100', '443','Text', 5);
